[package]
name = "broken-app"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true
split-debuginfo = "packed"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/DEBUG"]

[dependencies]

[dev-dependencies]
criterion = "0.8.2"


[[bench]]
name = "criterion"
path = "benches/criterion.rs"
harness = false
